# Generated by Django 5.2.6 on 2025-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ACCOUNTANT', 'Contador'), ('CLIENT', 'Cliente')], default='CLIENT', help_text='Determina el nivel de acceso del usuario.', max_length=20),
        ),
    ]
