# Generated by Django 5.2.6 on 2025-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit Card"),
                    ("transfer", "Bank Transfer"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
