# Generated by Django 5.2.6 on 2025-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta de crédito'), ('transfer', 'Transferencia bancaria')], default='cash', max_length=20),
        ),
    ]
