# Generated by Django 5.2.6 on 2025-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_alter_invoice_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
