# Generated by Django 5.2.6 on 2025-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_invoice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("A", "Factura A"), ("B", "Factura B"), ("C", "Factura C")],
                default="B",
                max_length=1,
            ),
        ),
    ]
