# Generated by Django 5.2.6 on 2025-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tax_id",
                    models.CharField(
                        help_text="CUIT or tax identification number", max_length=20
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
